"""Product download path

Revision ID: 00e0b6ed9b34
Revises: a8679a4d7166
Create Date: 2020-03-02 14:06:10.487266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e0b6ed9b34'
down_revision = 'a8679a4d7166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('download_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'download_path')
    # ### end Alembic commands ###
