"""Record minutes to float

Revision ID: 157a61ff25e8
Revises: d8d773bc5ce2
Create Date: 2021-04-02 13:54:20.937944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '157a61ff25e8'
down_revision = 'd8d773bc5ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page', 'body',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=10000000),
               existing_nullable=True)
    op.alter_column('page', 'notes',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=5000000),
               existing_nullable=True)
    op.alter_column('page_version', 'body',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=10000000),
               existing_nullable=True)
    op.alter_column('page_version', 'notes',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(length=5000000),
               existing_nullable=True)
    op.alter_column('record', 'minutes',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('record', 'minutes',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('page_version', 'notes',
               existing_type=sa.Text(length=5000000),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('page_version', 'body',
               existing_type=sa.Text(length=10000000),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('page', 'notes',
               existing_type=sa.Text(length=5000000),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('page', 'body',
               existing_type=sa.Text(length=10000000),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###
