"""Product.active

Revision ID: 334ed00a5401
Revises: dab2ae085b83
Create Date: 2019-12-19 13:08:07.609447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334ed00a5401'
down_revision = 'dab2ae085b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'active')
    # ### end Alembic commands ###
