"""Add Record

Revision ID: 34c2016fd7d6
Revises: 334ed00a5401
Create Date: 2020-01-06 10:26:46.022831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c2016fd7d6'
down_revision = '334ed00a5401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('words', sa.Integer(), nullable=True),
    sa.Column('start_words', sa.Integer(), nullable=False),
    sa.Column('end_words', sa.Integer(), nullable=False),
    sa.Column('overall_words', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    # ### end Alembic commands ###
