"""Add author's note

Revision ID: 422b898cbfd3
Revises: 93b8a979c5dd
Create Date: 2020-02-20 08:23:15.431972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422b898cbfd3'
down_revision = '93b8a979c5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('author_note', sa.String(length=5000), nullable=True))
    op.add_column('page_version', sa.Column('author_note', sa.String(length=5000), nullable=True))
    op.add_column('page_version', sa.Column('author_note_location', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_version', 'author_note_location')
    op.drop_column('page_version', 'author_note')
    op.drop_column('page', 'author_note')
    # ### end Alembic commands ###
