"""definitions

Revision ID: 44077c9504c9
Revises: 67240b207c34
Create Date: 2019-07-28 05:24:34.831541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44077c9504c9'
down_revision = '67240b207c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('body', sa.String(length=5000), nullable=False),
    sa.Column('hidden_body', sa.String(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_defs',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['definition.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'definition_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_defs')
    op.drop_table('definition')
    # ### end Alembic commands ###
