"""Page notify group

Revision ID: 4d86ed0f64e7
Revises: 00e0b6ed9b34
Create Date: 2020-03-06 07:55:06.753449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d86ed0f64e7'
down_revision = '00e0b6ed9b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('notify_group', sa.String(length=100), nullable=True))
    op.add_column('page_version', sa.Column('notify_group', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_version', 'notify_group')
    op.drop_column('page', 'notify_group')
    # ### end Alembic commands ###
