"""Definition linked tag

Revision ID: 4d9d4e0e52db
Revises: 63811d946c28
Create Date: 2019-11-14 15:38:39.267182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9d4e0e52db'
down_revision = '63811d946c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definition', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.add_column('definition', sa.Column('type', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'definition', 'tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'definition', type_='foreignkey')
    op.drop_column('definition', 'type')
    op.drop_column('definition', 'tag_id')
    # ### end Alembic commands ###
