"""Product Sale Price

Revision ID: 524dbf864261
Revises: 8b55ef2ea1dc
Create Date: 2020-02-26 14:13:48.765430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524dbf864261'
down_revision = '8b55ef2ea1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('sale_price', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'sale_price')
    # ### end Alembic commands ###
