"""Category icon

Revision ID: 5765f4ee6de3
Revises: e9d11a13e71b
Create Date: 2021-03-09 08:03:55.644894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5765f4ee6de3'
down_revision = 'e9d11a13e71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('category', sa.Column('icon', sa.String(length=150), nullable=True))
    op.add_column('category', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('category', sa.Column('updater_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'user', ['updater_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'updater_id')
    op.drop_column('category', 'updated')
    op.drop_column('category', 'icon')
    op.drop_column('category', 'created')
    # ### end Alembic commands ###
