"""Add product slug

Revision ID: 59f006063c86
Revises: aa980fb54fcf
Create Date: 2020-02-18 10:50:53.867300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f006063c86'
down_revision = 'aa980fb54fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('slug', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'slug')
    # ### end Alembic commands ###
