"""User timezone

Revision ID: 67240b207c34
Revises: fc110eefbdb1
Create Date: 2019-05-12 14:42:04.408597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67240b207c34'
down_revision = 'fc110eefbdb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    # ### end Alembic commands ###
