"""Add record.minutes and words_per_minute

Revision ID: 89a439863ee8
Revises: fc419f6ad59c
Create Date: 2020-01-07 12:56:05.716824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a439863ee8'
down_revision = 'fc419f6ad59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('minutes', sa.Integer(), nullable=True))
    op.add_column('record', sa.Column('words_per_minute', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'words_per_minute')
    op.drop_column('record', 'minutes')
    # ### end Alembic commands ###
