"""Product On Sale

Revision ID: 8b55ef2ea1dc
Revises: c31ce21dfcf2
Create Date: 2020-02-26 13:55:57.534348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b55ef2ea1dc'
down_revision = 'c31ce21dfcf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('on_sale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'on_sale')
    # ### end Alembic commands ###
