"""Product linked pages

Revision ID: 93b8a979c5dd
Revises: 59f006063c86
Create Date: 2020-02-19 08:18:35.173361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b8a979c5dd'
down_revision = '59f006063c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('linked_page_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'page', ['linked_page_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'linked_page_id')
    # ### end Alembic commands ###
