"""Add author's note

Revision ID: 9f33243b735e
Revises: 422b898cbfd3
Create Date: 2020-02-20 08:24:32.425976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f33243b735e'
down_revision = '422b898cbfd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('author_note_location', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'author_note_location')
    # ### end Alembic commands ###
