"""Link Icon and Format

Revision ID: a8679a4d7166
Revises: 524dbf864261
Create Date: 2020-02-28 08:30:18.512757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8679a4d7166'
down_revision = '524dbf864261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('format', sa.String(length=100), nullable=True))
    op.add_column('link', sa.Column('icon', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'icon')
    op.drop_column('link', 'format')
    # ### end Alembic commands ###
