"""Product prices upgrade

Revision ID: a8935b69065d
Revises: f55537e3f06d
Create Date: 2023-12-24 06:59:11.442755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8935b69065d'
down_revision = 'f55537e3f06d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=12), nullable=True),
    sa.Column('currency', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('direct', sa.Boolean(), nullable=True),
    sa.Column('shipping', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('direct_sale', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('shipping_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscription_required', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('subscription_required')
        batch_op.drop_column('shipping_required')
        batch_op.drop_column('direct_sale')
        batch_op.drop_column('type')

    op.drop_table('price')
    # ### end Alembic commands ###
