"""Add Definition.active

Revision ID: aa980fb54fcf
Revises: 89a439863ee8
Create Date: 2020-01-09 14:15:50.557243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa980fb54fcf'
down_revision = '89a439863ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definition', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('definition', 'active')
    # ### end Alembic commands ###
