"""Nullable definition hidden_body

Revision ID: b6aeee8baac1
Revises: 44077c9504c9
Create Date: 2019-07-29 09:47:18.397394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6aeee8baac1'
down_revision = '44077c9504c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('definition', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.alter_column('definition', 'hidden_body',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5000),
               nullable=True)
    op.create_foreign_key(None, 'definition', 'page', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'definition', type_='foreignkey')
    op.alter_column('definition', 'hidden_body',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5000),
               nullable=False)
    op.drop_column('definition', 'parent_id')
    # ### end Alembic commands ###
