"""Add subscribe date

Revision ID: fc110eefbdb1
Revises: f30c4ce8ccb3
Create Date: 2019-05-10 18:57:42.020839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc110eefbdb1'
down_revision = 'f30c4ce8ccb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('sub_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'sub_date')
    # ### end Alembic commands ###
