"""Record Comment

Revision ID: fc419f6ad59c
Revises: 34c2016fd7d6
Create Date: 2020-01-06 11:17:55.913967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc419f6ad59c'
down_revision = '34c2016fd7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('comment', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'comment')
    # ### end Alembic commands ###
